name: CowWand
version: '${project.version}'
main: rivraff.com.github.cowwand.CowWand
api-version: 1.19
authors: [ RivRaff ]
description: The power of the cows. Creates a wand which you can fire explosive cows from. Has permissions for wands[TBD, not yet  complete.].
permissions:
        cowwand.use:
            default: true
commands:
    firecow:
        description: Fires an explosive cow in the direction you are facing. Cow without the wand.
        usage: /firecow